In [6]:

import torch

x = torch.arange(12)
print(x)

print(x.shape)

X = x.reshape(3,4)

print(X)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [10]:
torch.ones((2,3,4))

torch.randn((2,4,5))

torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [15]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

print(x + y)
print(x - y)
print(x * y)
print(x ** y)
print(x / y)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([ 1.,  4., 16., 64.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])


In [16]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [17]:
X = torch.arange(12, dtype=torch.float64).reshape((3,4));

Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]);

print(torch.cat((X, Y), dim=0)) # 按行进行拼接。这个意思是不改变每个矩阵的行向量

print(torch.cat((X, Y), dim=1)) # 按列进行拼接。这个意思是不改变每个矩阵的列向量

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=torch.float64)
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=torch.float64)


In [19]:
X==Y

X.sum()

tensor(66., dtype=torch.float64)

In [20]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:

# 需要跟踪a和b的广播机制
a + b
    

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [23]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [24]:
assert(X[0, 3] == 3)

In [29]:
Y = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Y的地址为：',id(Y))
Y[:] = X + Y
print('Y的地址为：',id(Y))

Y的地址为： 2364084651824
Y的地址为： 2364084651824


In [31]:
X < Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])