In [11]:
import torch

x = torch.arange(4.0,requires_grad=True)
x


tensor([0., 1., 2., 3.], requires_grad=True)

In [12]:
x.grad

In [13]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [14]:
x.grad == 4 * x

False

In [15]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [16]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [23]:
x.grad.zero_()
y = x * x 
y.sum().backward()
x.grad



tensor([0., 2., 4., 6.])

In [ ]:
x.grad.zero_()
y = x * x 
u = y.detach()

z = u * x

z.sum().backward()

